[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "backend/netlify/functions/"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[build]
  publish = "frontend/"